# Generated by Django 3.1.3 on 2020-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='testbps',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
    ]
