# Generated by Django 3.1.3 on 2020-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_userdata_testbps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ca',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='chol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='exang',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'N0')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='fbs',
            field=models.IntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='oldpeak',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'HAVING ST-T'), (2, 'HYPERTROPHY')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='slope',
            field=models.IntegerField(choices=[(1, 'UP_SLOPING'), (2, 'FLAT'), (3, 'DOWN_SLOPING')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='thal',
            field=models.IntegerField(choices=[(3, 'NORMAL'), (6, 'FIXED DEFECT'), (7, 'REVERSIBLE DEFECT')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='thalch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cp',
            field=models.IntegerField(choices=[(0, 'ATYPICAL ANGINA'), (1, 'TYPICAL ANGINA'), (2, 'ASYMPTOMATIC'), (3, 'NON ANGINAL PAIN')]),
        ),
    ]
