# Generated by Django 3.1.3 on 2020-12-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201203_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('phoneNo', models.IntegerField()),
                ('email', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'MALE'), (0, 'FEMALE')])),
                ('speciality', models.CharField(max_length=20)),
            ],
        ),
    ]
