# Generated by Django 3.1.3 on 2020-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='sex',
            field=models.IntegerField(choices=[(1, 'MALE'), (0, 'FEMALE')], default=1),
            preserve_default=False,
        ),
    ]
