# Generated by Django 3.1.3 on 2020-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20201204_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doc',
            name='email',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='add_doc',
            name='phoneNo',
            field=models.CharField(max_length=10),
        ),
    ]
