# Generated by Django 3.1.3 on 2020-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20201205_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doc',
            name='email',
            field=models.CharField(max_length=64),
        ),
    ]
